version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: sms-sender-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "4200:80"

    php-fpm:
      build: docker/php-fpm
      container_name: sms-sender-php-fpm
      working_dir: /application
      volumes:
        - .:/application

